"""Unified exception hierarchy for JARVIS.

This module provides a consistent error handling system across CLI, API, and models.
All JARVIS-specific exceptions inherit from JarvisError, enabling consistent handling.

Note: This module is now a facade for the decomposed exceptions in jarvis.core.exceptions.
New code should ideally import from jarvis.core.exceptions directly.
"""

from __future__ import annotations

from jarvis.core.exceptions import (
    CalendarAccessError,
    CalendarCreateError,
    CalendarError,
    ConfigurationError,
    ConversationNotFoundError,
    DatabaseError,
    DiskResourceError,
    EmbeddingError,
    ErrorCode,
    EventParseError,
    ExperimentConfigError,
    ExperimentError,
    ExperimentNotFoundError,
    ExportError,
    FeedbackError,
    FeedbackInvalidActionError,
    FeedbackNotFoundError,
    GraphContactNotFoundError,
    GraphError,
    JarvisError,
    MemoryResourceError,
    ModelError,
    ModelGenerationError,
    ModelLoadError,
    ResourceError,
    TaskError,
    TaskExecutionError,
    TaskNotFoundError,
    ValidationError,
    calendar_permission_denied,
    imessage_db_not_found,
    imessage_permission_denied,
    iMessageAccessError,
    iMessageError,
    iMessageQueryError,
    jarvis_error,
    model_generation_timeout,
    model_not_found,
    model_out_of_memory,
    validation_required,
    validation_type_error,
)

__all__ = [
    "ErrorCode",
    "JarvisError",
    "ConfigurationError",
    "ModelError",
    "ModelLoadError",
    "ModelGenerationError",
    "iMessageError",
    "iMessageAccessError",
    "iMessageQueryError",
    "ConversationNotFoundError",
    "ValidationError",
    "ResourceError",
    "MemoryResourceError",
    "DiskResourceError",
    "TaskError",
    "TaskNotFoundError",
    "TaskExecutionError",
    "CalendarError",
    "CalendarAccessError",
    "CalendarCreateError",
    "EventParseError",
    "ExperimentError",
    "ExperimentNotFoundError",
    "ExperimentConfigError",
    "FeedbackError",
    "FeedbackNotFoundError",
    "FeedbackInvalidActionError",
    "GraphError",
    "GraphContactNotFoundError",
    "DatabaseError",
    "ExportError",
    "EmbeddingError",
    "model_not_found",
    "model_out_of_memory",
    "imessage_permission_denied",
    "imessage_db_not_found",
    "calendar_permission_denied",
    "validation_required",
    "validation_type_error",
    "model_generation_timeout",
    "jarvis_error",
]
