"""Apply gold labels to fact_goldset_round2/fact_goldset_400.csv"""
import csv
import sys

INPUT = "training_data/fact_goldset_round2/fact_goldset_400.csv"
OUTPUT = "training_data/fact_goldset_round2/fact_goldset_400.csv"

# (gold_keep, gold_fact_type, gold_subject, gold_subject_resolution, gold_anchor_message_id, gold_notes)
# Using coarse types: health, relationship, preference, work, education, hobby, location, other
# Subjects: me, other_participant, or explicit name (dad, mom, brother, Sid, etc.)
LABELS = {
    "fact_gs_0001": (0, "", "", "", "", "joke about car/money"),
    "fact_gs_0002": (0, "", "", "", "", "transient; mom willing to go to restaurant"),
    "fact_gs_0003": (0, "", "", "", "", "question about attendance; health facts in context only"),
    "fact_gs_0004": (1, "relationship", "me", "speaker", "", "has a brother"),
    "fact_gs_0005": (1, "health", "brother", "named_entity", "", "other participant's brother went to ER; fine now"),
    "fact_gs_0006": (0, "", "", "", "", "exclamation"),
    "fact_gs_0007": (0, "", "", "", "", "time; chiropractor in context only"),
    "fact_gs_0008": (1, "location", "other_participant", "other_participant", "", "lives ~20 min from UTD; has a brother; mom nearby"),
    "fact_gs_0009": (0, "", "", "", "", "acknowledgment"),
    "fact_gs_0010": (0, "", "", "", "", "joking about painkillers"),
    "fact_gs_0011": (0, "", "", "", "", "reaction"),
    "fact_gs_0012": (0, "", "", "", "", "frisbee opinion"),
    "fact_gs_0013": (0, "", "", "", "", "no fact"),
    "fact_gs_0014": (0, "", "", "", "", "minimal"),
    "fact_gs_0015": (1, "relationship", "me", "speaker", "", "mom is in India; has brother Mihir; mom coming back the 28th"),
    "fact_gs_0016": (0, "", "", "", "", "reaction to video"),
    "fact_gs_0017": (0, "", "", "", "", "request for garbage bags"),
    "fact_gs_0018": (0, "", "", "", "", "insult/joke"),
    "fact_gs_0019": (0, "", "", "", "", "momentary sports trade opinion"),
    "fact_gs_0020": (0, "", "", "", "", "reaction"),
    "fact_gs_0021": (0, "", "", "", "", "reaction wrapper"),
    "fact_gs_0022": (1, "work", "dad", "named_entity", "", "dad and cousin work at Facebook and Intuit respectively"),
    "fact_gs_0023": (0, "", "", "", "", "basketball performance comment"),
    "fact_gs_0024": (0, "", "", "", "", "no fact in main msg; frozen food/aunt in context"),
    "fact_gs_0025": (0, "", "", "", "", "expression of love; not factual"),
    "fact_gs_0026": (1, "preference", "other_participant", "other_participant", "", "likes dolmas"),
    "fact_gs_0027": (0, "", "", "", "", "insult"),
    "fact_gs_0028": (0, "", "", "", "", "sports game reaction"),
    "fact_gs_0029": (0, "", "", "", "", "playful affection"),
    "fact_gs_0030": (0, "", "", "", "", "ambiguous; walnut may be pet name"),
    "fact_gs_0031": (0, "", "", "", "", "transient event; brother took rock from beach"),
    "fact_gs_0032": (0, "", "", "", "", "gossip about Tara"),
    "fact_gs_0033": (0, "", "", "", "", "asking dad about tech; transient"),
    "fact_gs_0034": (0, "", "", "", "", "transient; mom didn't visit"),
    "fact_gs_0035": (0, "", "", "", "", "fantasy football frustration about Najee Harris"),
    "fact_gs_0036": (0, "", "", "", "", "reaction"),
    "fact_gs_0037": (1, "health", "me", "speaker", "", "in the hospital (from context: I'm kinda in the hospital)"),
    "fact_gs_0038": (0, "", "", "", "", "playful insult"),
    "fact_gs_0039": (1, "other", "me", "speaker", "", "personality: tends to repress emotions and feelings"),
    "fact_gs_0040": (1, "health", "me", "speaker", "", "receiving drugs/antibiotics; inconclusive test results"),
    "fact_gs_0041": (1, "relationship", "other_participant", "other_participant", "", "has a brother; dropping brother at SFO"),
    "fact_gs_0042": (1, "education", "me", "speaker", "", "planning to graduate fall 2024; discussing lease length with dad"),
    "fact_gs_0043": (0, "", "", "", "", "vague 'i like this' about furniture/plan"),
    "fact_gs_0044": (0, "", "", "", "", "about a sports game view"),
    "fact_gs_0045": (0, "", "", "", "", "logistics"),
    "fact_gs_0046": (0, "", "", "", "", "transient; slept wrong"),
    "fact_gs_0047": (0, "", "", "", "", "asking about someone"),
    "fact_gs_0048": (0, "", "", "", "", "tagging people"),
    "fact_gs_0049": (0, "", "", "", "", "question about travel direction"),
    "fact_gs_0050": (0, "", "", "", "", "transient; dad behind them"),
    "fact_gs_0051": (0, "", "", "", "", "vague relationship feeling"),
    "fact_gs_0052": (0, "", "", "", "", "literal filler text"),
    "fact_gs_0053": (0, "", "", "", "", "about keeping someone up"),
    "fact_gs_0054": (0, "", "", "", "", "apartment maintenance anecdote"),
    "fact_gs_0055": (0, "", "", "", "", "joking"),
    "fact_gs_0056": (0, "", "", "", "", "vague 'rough'; 2yr relationship breakup in context only"),
    "fact_gs_0057": (1, "other", "other_participant", "other_participant", "", "on Virgin Mobile; switching to T-Mobile; dad found deal"),
    "fact_gs_0058": (0, "", "", "", "", "compliment"),
    "fact_gs_0059": (0, "", "", "", "", "reaction"),
    "fact_gs_0060": (0, "", "", "", "", "transient restaurant recommendation"),
    "fact_gs_0061": (0, "", "", "", "", "frisbee joke"),
    "fact_gs_0062": (0, "", "", "", "", "location reference"),
    "fact_gs_0063": (0, "", "", "", "", "transient logistics"),
    "fact_gs_0064": (0, "", "", "", "", "fantasy basketball opinion"),
    "fact_gs_0065": (0, "", "", "", "", "sports commentary"),
    "fact_gs_0066": (0, "", "", "", "", "about reselling items"),
    "fact_gs_0067": (0, "", "", "", "", "vague"),
    "fact_gs_0068": (0, "", "", "", "", "main msg is 'i wanna grab u'; Queens location in context only"),
    "fact_gs_0069": (0, "", "", "", "", "declining help; health recovery in context only"),
    "fact_gs_0070": (1, "work", "other_participant", "other_participant", "", "likes product management; seeking PM experience; uses Python and SQL for data science"),
    "fact_gs_0071": (0, "", "", "", "", "greeting"),
    "fact_gs_0072": (0, "", "", "", "", "CS homework question"),
    "fact_gs_0073": (0, "", "", "", "", "parents live nearby; anecdote"),
    "fact_gs_0074": (0, "", "", "", "", "no fact"),
    "fact_gs_0075": (0, "", "", "", "", "transient; dad working from home today"),
    "fact_gs_0076": (1, "preference", "me", "speaker", "", "LOVES idli and dosa"),
    "fact_gs_0077": (0, "", "", "", "", "birthday wish"),
    "fact_gs_0078": (0, "", "", "", "", "shoe news; RA training in context"),
    "fact_gs_0079": (0, "", "", "", "", "funny dad theory about Draymond"),
    "fact_gs_0080": (1, "other", "other_participant", "other_participant", "", "deeply involved in Swadhyay/yuva kendra; values self-development"),
    "fact_gs_0081": (0, "", "", "", "", "acknowledgment"),
    "fact_gs_0082": (1, "location", "other_participant", "other_participant", "", "lives in San Jose area; has a sister"),
    "fact_gs_0083": (1, "relationship", "me", "speaker", "", "has brother who goes to school; drives to Napa for him"),
    "fact_gs_0084": (0, "", "", "", "", "checking on someone"),
    "fact_gs_0085": (1, "health", "me", "speaker", "", "prescription SER at CVS 43950 Pacific Common; Dr. J Moore"),
    "fact_gs_0086": (0, "", "", "", "", "asked mom; vague"),
    "fact_gs_0087": (1, "hobby", "me", "speaker", "", "plays/watches cricket; mom makes lunch"),
    "fact_gs_0088": (0, "", "", "", "", "no fact in main msg; at work in context"),
    "fact_gs_0089": (1, "location", "other_participant", "other_participant", "", "used to live in Cupertino"),
    "fact_gs_0090": (0, "", "", "", "", "reaction"),
    "fact_gs_0091": (0, "", "", "", "", "greeting/joke"),
    "fact_gs_0092": (0, "", "", "", "", "vague sports format opinion"),
    "fact_gs_0093": (0, "", "", "", "", "figurative; fantasy basketball context"),
    "fact_gs_0094": (0, "", "", "", "", "question"),
    "fact_gs_0095": (1, "relationship", "other_participant", "other_participant", "", "has a roommate at Stanford; gets along well"),
    "fact_gs_0096": (1, "health", "me", "speaker", "", "in hospital; dad flew in"),
    "fact_gs_0097": (0, "", "", "", "", "transient; cancelled appointments"),
    "fact_gs_0098": (0, "", "", "", "", "transient; mom bringing bags for move"),
    "fact_gs_0099": (0, "", "", "", "", "joke"),
    "fact_gs_0100": (0, "", "", "", "", "typo greeting"),
    "fact_gs_0101": (1, "preference", "me", "speaker", "", "mom makes falafel"),
    "fact_gs_0102": (1, "preference", "other_participant", "other_participant", "", "hates driving in SF; prefers taking BART"),
    "fact_gs_0103": (0, "", "", "", "", "exclamation"),
    "fact_gs_0104": (1, "hobby", "me", "speaker", "", "likes reading"),
    "fact_gs_0105": (1, "other", "other_participant", "other_participant", "", "mom converted into their faith when younger in Taiwan; no longer tied to any faith"),
    "fact_gs_0106": (0, "", "", "", "", "acknowledgment"),
    "fact_gs_0107": (0, "", "", "", "", "acknowledgment"),
    "fact_gs_0108": (0, "", "", "", "", "transient; mom picking up"),
    "fact_gs_0109": (0, "", "", "", "", "transient; watching game with dad"),
    "fact_gs_0110": (0, "", "", "", "", "trivial; texting habits"),
    "fact_gs_0111": (0, "", "", "", "", "vague"),
    "fact_gs_0112": (0, "", "", "", "", "nevermind"),
    "fact_gs_0113": (1, "work", "other_participant", "other_participant", "", "teaches a class; loves teaching"),
    "fact_gs_0114": (0, "", "", "", "", "vague about closet/clothes"),
    "fact_gs_0115": (0, "", "", "", "", "transient; going to Caspian with mom"),
    "fact_gs_0116": (1, "location", "other_participant", "other_participant", "", "moved out from home; dad doing house projects"),
    "fact_gs_0117": (0, "", "", "", "", "transient; resting, head hurt in context"),
    "fact_gs_0118": (0, "", "", "", "", "transient; brother watching something"),
    "fact_gs_0119": (0, "", "", "", "", "vague dislike"),
    "fact_gs_0120": (0, "", "", "", "", "Venmo request"),
    "fact_gs_0121": (0, "", "", "", "", "reaction; energy company switch in context"),
    "fact_gs_0122": (0, "", "", "", "", "question about travel"),
    "fact_gs_0123": (1, "other", "other_participant", "other_participant", "", "is 20 years old; has a brother"),
    "fact_gs_0124": (0, "", "", "", "", "no fact"),
    "fact_gs_0125": (0, "", "", "", "", "acknowledgment"),
    "fact_gs_0126": (1, "education", "brother", "named_entity", "", "speaker's brother at culinary school; externship in Delaware"),
    "fact_gs_0127": (0, "", "", "", "", "acknowledgment"),
    "fact_gs_0128": (1, "health", "other_participant", "other_participant", "", "family member unwell; mom leaving for India"),
    "fact_gs_0129": (0, "", "", "", "", "question fragment"),
    "fact_gs_0130": (1, "relationship", "other_participant", "other_participant", "", "has a sister"),
    "fact_gs_0131": (0, "", "", "", "", "vague"),
    "fact_gs_0132": (0, "", "", "", "", "reaction"),
    "fact_gs_0133": (0, "", "", "", "", "reaction"),
    "fact_gs_0134": (0, "", "", "", "", "tech industry opinion"),
    "fact_gs_0135": (0, "", "", "", "", "reaction"),
    "fact_gs_0136": (1, "relationship", "me", "speaker", "", "has crush; she's from Princeton"),
    "fact_gs_0137": (0, "", "", "", "", "transient graduation event"),
    "fact_gs_0138": (0, "", "", "", "", "question about time"),
    "fact_gs_0139": (0, "", "", "", "", "sports commentary"),
    "fact_gs_0140": (0, "", "", "", "", "relaying affection"),
    "fact_gs_0141": (0, "", "", "", "", "about communication style"),
    "fact_gs_0142": (0, "", "", "", "", "reaction wrapper"),
    "fact_gs_0143": (1, "work", "other_participant", "other_participant", "", "works at LendingTree"),
    "fact_gs_0144": (1, "other", "other_participant", "other_participant", "", "teaches Sanskrit on weekends; reads and meditates daily; works in engineering; involved in Swadhyay"),
    "fact_gs_0145": (1, "preference", "other_participant", "other_participant", "", "likes thick french fries"),
    "fact_gs_0146": (0, "", "", "", "", "transient; likes red furniture"),
    "fact_gs_0147": (0, "", "", "", "", "conversational"),
    "fact_gs_0148": (1, "health", "me", "speaker", "", "foot hurts and swollen"),
    "fact_gs_0149": (0, "", "", "", "", "transient logistics"),
    "fact_gs_0150": (0, "", "", "", "", "playful"),
    "fact_gs_0151": (0, "", "", "", "", "transient schedule; work at 7"),
    "fact_gs_0152": (1, "preference", "other_participant", "other_participant", "", "likes Santa Barbara"),
    "fact_gs_0153": (0, "", "", "", "", "no fact; eye exam place in context"),
    "fact_gs_0154": (0, "", "", "", "", "transient car logistics for brother"),
    "fact_gs_0155": (0, "", "", "", "", "acknowledgment"),
    "fact_gs_0156": (0, "", "", "", "", "joking insult"),
    "fact_gs_0157": (0, "", "", "", "", "anecdote about waxing"),
    "fact_gs_0158": (1, "relationship", "other_participant", "other_participant", "", "has a sister"),
    "fact_gs_0159": (0, "", "", "", "", "transient; someone in shower"),
    "fact_gs_0160": (1, "other", "other_participant", "other_participant", "", "dad retiring; parents plan to sell house and travel in RV"),
    "fact_gs_0161": (0, "", "", "", "", "trivial; upgraded mom's laptop RAM"),
    "fact_gs_0162": (0, "", "", "", "", "expression of affection"),
    "fact_gs_0163": (0, "", "", "", "", "reaction"),
    "fact_gs_0164": (0, "", "", "", "", "one-word response; massage subscription in context"),
    "fact_gs_0165": (0, "", "", "", "", "vague past tense liking"),
    "fact_gs_0166": (0, "", "", "", "", "playful"),
    "fact_gs_0167": (0, "", "", "", "", "reaction"),
    "fact_gs_0168": (0, "", "", "", "", "transient; helping mom"),
    "fact_gs_0169": (0, "", "", "", "", "car shopping discussion"),
    "fact_gs_0170": (0, "", "", "", "", "sports opinion about Randy Gregory"),
    "fact_gs_0171": (1, "other", "me", "speaker", "", "dad leaving for India on the 22nd; family ties to India"),
    "fact_gs_0172": (1, "health", "me", "speaker", "", "bad sleep; depression; lack of motivation"),
    "fact_gs_0173": (0, "", "", "", "", "transient location; in Vegas"),
    "fact_gs_0174": (0, "", "", "", "", "time reference"),
    "fact_gs_0175": (0, "", "", "", "", "about sourdough/baking"),
    "fact_gs_0176": (0, "", "", "", "", "reaction; job at Intuit in context"),
    "fact_gs_0177": (0, "", "", "", "", "reaction"),
    "fact_gs_0178": (0, "", "", "", "", "fantasy basketball draft opinion"),
    "fact_gs_0179": (0, "", "", "", "", "transient schedule; mom gets home at 4:30"),
    "fact_gs_0180": (1, "other", "other_participant", "other_participant", "", "translates for mom at doctor appointments"),
    "fact_gs_0181": (0, "", "", "", "", "question about housing"),
    "fact_gs_0182": (1, "other", "other_participant", "other_participant", "", "dad turned 60; family trip to Egypt"),
    "fact_gs_0183": (0, "", "", "", "", "insult"),
    "fact_gs_0184": (0, "", "", "", "", "acknowledgment"),
    "fact_gs_0185": (0, "", "", "", "", "question; career facts in context from other person"),
    "fact_gs_0186": (0, "", "", "", "", "busy this weekend"),
    "fact_gs_0187": (1, "preference", "me", "speaker", "", "loved Harry Potter; read series ~25+ times"),
    "fact_gs_0188": (0, "", "", "", "", "about asking dad"),
    "fact_gs_0189": (0, "", "", "", "", "vague agreement"),
    "fact_gs_0190": (0, "", "", "", "", "vague; about an apartment"),
    "fact_gs_0191": (0, "", "", "", "", "about forgetting to play fantasy"),
    "fact_gs_0192": (1, "work", "other_participant", "other_participant", "", "teaches at IHS; online teaching per bell schedule"),
    "fact_gs_0193": (0, "", "", "", "", "insult"),
    "fact_gs_0194": (1, "work", "other_participant", "other_participant", "", "works (off for xmas); brother in town"),
    "fact_gs_0195": (0, "", "", "", "", "transient; mom sent bundt cakes"),
    "fact_gs_0196": (0, "", "", "", "", "reaction"),
    "fact_gs_0197": (0, "", "", "", "", "transient; dropped off dad"),
    "fact_gs_0198": (0, "", "", "", "", "suggesting to ask mom"),
    "fact_gs_0199": (0, "", "", "", "", "transient; helping brother"),
    "fact_gs_0200": (0, "", "", "", "", "reaction to culinary school mention"),
    "fact_gs_0201": (0, "", "", "", "", "transient tech issue; brother's phone bootloop"),
    "fact_gs_0202": (0, "", "", "", "", "one word"),
    "fact_gs_0203": (0, "", "", "", "", "transient logistics; volleyball and brother"),
    "fact_gs_0204": (0, "", "", "", "", "ultimate frisbee drill feedback"),
    "fact_gs_0205": (0, "", "", "", "", "tech humor about sudo"),
    "fact_gs_0206": (0, "", "", "", "", "sports commentary"),
    "fact_gs_0207": (0, "", "", "", "", "eating at home"),
    "fact_gs_0208": (0, "", "", "", "", "transient"),
    "fact_gs_0209": (0, "", "", "", "", "transient schedule; dentist"),
    "fact_gs_0210": (0, "", "", "", "", "vague"),
    "fact_gs_0211": (0, "", "", "", "", "transient; dad WFH today"),
    "fact_gs_0212": (0, "", "", "", "", "playful expression about Kishan"),
    "fact_gs_0213": (0, "", "", "", "", "transient"),
    "fact_gs_0214": (1, "hobby", "mom", "named_entity", "", "speaker's mom does yoga"),
    "fact_gs_0215": (0, "", "", "", "", "frisbee economics"),
    "fact_gs_0216": (0, "", "", "", "", "reaction"),
    "fact_gs_0217": (1, "hobby", "brother", "named_entity", "", "speaker's brother bakes/makes cakes"),
    "fact_gs_0218": (1, "other", "other_participant", "other_participant", "", "shares car with brother"),
    "fact_gs_0219": (0, "", "", "", "", "anecdote about planes"),
    "fact_gs_0220": (1, "education", "brother", "named_entity", "", "speaker's brother doing externship for culinary school"),
    "fact_gs_0221": (1, "relationship", "other_participant", "other_participant", "", "has a sister; wants to bike across Golden Gate Bridge"),
    "fact_gs_0222": (0, "", "", "", "", "signing a message"),
    "fact_gs_0223": (0, "", "", "", "", "about a person's vibe"),
    "fact_gs_0224": (0, "", "", "", "", "transient; dad will be home"),
    "fact_gs_0225": (0, "", "", "", "", "sports lineup preference"),
    "fact_gs_0226": (0, "", "", "", "", "sports opinion about Chet"),
    "fact_gs_0227": (0, "", "", "", "", "vague; work busy in context"),
    "fact_gs_0228": (1, "other", "me", "speaker", "", "involved in Swadhyay; dad works; considering taking car to Dallas"),
    "fact_gs_0229": (1, "location", "me", "speaker", "", "planning to move back to California; looking for a job"),
    "fact_gs_0230": (0, "", "", "", "", "transient; calling dad"),
    "fact_gs_0231": (1, "preference", "other_participant", "other_participant", "", "likes Peter Zeihan books; interested in geopolitics"),
    "fact_gs_0232": (0, "", "", "", "", "about Apple auto-behavior"),
    "fact_gs_0233": (0, "", "", "", "", "reaction"),
    "fact_gs_0234": (0, "", "", "", "", "about dad not being on board"),
    "fact_gs_0235": (0, "", "", "", "", "vague; about a photo"),
    "fact_gs_0236": (0, "", "", "", "", "transient; brother started work"),
    "fact_gs_0237": (0, "", "", "", "", "reaction"),
    "fact_gs_0238": (0, "", "", "", "", "transient; hates some current classes"),
    "fact_gs_0239": (1, "other", "other_participant", "other_participant", "", "personality: hates letting people down"),
    "fact_gs_0240": (0, "", "", "", "", "vague"),
    "fact_gs_0241": (0, "", "", "", "", "playful"),
    "fact_gs_0242": (1, "other", "other_participant", "other_participant", "", "teaches Sanskrit on weekends; works in engineering; reads and meditates daily"),
    "fact_gs_0243": (0, "", "", "", "", "acknowledgment"),
    "fact_gs_0244": (0, "", "", "", "", "about mom's suggestion re Sahil"),
    "fact_gs_0245": (0, "", "", "", "", "transient; learning to drive"),
    "fact_gs_0246": (0, "", "", "", "", "transient; mom took to at-home business"),
    "fact_gs_0247": (0, "", "", "", "", "tea for mom"),
    "fact_gs_0248": (0, "", "", "", "", "insurance policy detail"),
    "fact_gs_0249": (1, "preference", "me", "speaker", "", "likes the Raiders (NFL)"),
    "fact_gs_0250": (1, "work", "other_participant", "other_participant", "", "teacher with pending return offer at a school; liked the school"),
    "fact_gs_0251": (0, "", "", "", "", "expression of love"),
    "fact_gs_0252": (1, "health", "me", "speaker", "", "has vestibular therapy appointments"),
    "fact_gs_0253": (0, "", "", "", "", "about gynecologist visit; transient"),
    "fact_gs_0254": (0, "", "", "", "", "reaction to video"),
    "fact_gs_0255": (1, "hobby", "me", "speaker", "", "cousin brought 17 books; avid reader; has a brother"),
    "fact_gs_0256": (1, "health", "me", "speaker", "", "experiencing pain; brother made a cake"),
    "fact_gs_0257": (0, "", "", "", "", "transient; picking up dad from airport"),
    "fact_gs_0258": (1, "hobby", "other_participant", "other_participant", "", "does daily 5K runs; has Xbox; dad made him pack it"),
    "fact_gs_0259": (0, "", "", "", "", "transient; waiting for mom; no car"),
    "fact_gs_0260": (0, "", "", "", "", "joke; iPhone 13 fact in context"),
    "fact_gs_0261": (0, "", "", "", "", "about mechanic knowing dad"),
    "fact_gs_0262": (1, "relationship", "other_participant", "other_participant", "", "romantic interest in someone; aspires to med school"),
    "fact_gs_0263": (0, "", "", "", "", "about starting something; internship Q in context"),
    "fact_gs_0264": (0, "", "", "", "", "no fact"),
    "fact_gs_0265": (0, "", "", "", "", "sports opinion about SGA"),
    "fact_gs_0266": (0, "", "", "", "", "acknowledgment"),
    "fact_gs_0267": (0, "", "", "", "", "sports opinion"),
    "fact_gs_0268": (0, "", "", "", "", "about dad's contact who developed Intel chips"),
    "fact_gs_0269": (0, "", "", "", "", "agreement"),
    "fact_gs_0270": (0, "", "", "", "", "question"),
    "fact_gs_0271": (0, "", "", "", "", "sports opinion about Clippers"),
    "fact_gs_0272": (0, "", "", "", "", "wanting to buy Catan"),
    "fact_gs_0273": (0, "", "", "", "", "transient; brother indoors during lockdown"),
    "fact_gs_0274": (0, "", "", "", "", "about someone moving to Dallas"),
    "fact_gs_0275": (0, "", "", "", "", "acknowledgment"),
    "fact_gs_0276": (0, "", "", "", "", "about buying team gear"),
    "fact_gs_0277": (0, "", "", "", "", "vague; about a class"),
    "fact_gs_0278": (0, "", "", "", "", "philosophical about friendship loss"),
    "fact_gs_0279": (0, "", "", "", "", "transient; dad says they're overweight"),
    "fact_gs_0280": (0, "", "", "", "", "tagging someone"),
    "fact_gs_0281": (1, "health", "me", "speaker", "", "symptoms and vertigo recurring; depression"),
    "fact_gs_0282": (0, "", "", "", "", "fantasy basketball trade discussion"),
    "fact_gs_0283": (0, "", "", "", "", "about needing membership"),
    "fact_gs_0284": (0, "", "", "", "", "vague; about honesty"),
    "fact_gs_0285": (0, "", "", "", "", "question about schedule"),
    "fact_gs_0286": (0, "", "", "", "", "transient; mom offering food"),
    "fact_gs_0287": (0, "", "", "", "", "question about sleep"),
    "fact_gs_0288": (0, "", "", "", "", "transient; about a professor"),
    "fact_gs_0289": (0, "", "", "", "", "transient emotional expression"),
    "fact_gs_0290": (0, "", "", "", "", "reaction"),
    "fact_gs_0291": (0, "", "", "", "", "vague; remembering calc"),
    "fact_gs_0292": (0, "", "", "", "", "vague; dad gets something from work"),
    "fact_gs_0293": (0, "", "", "", "", "reconnecting; LA in context"),
    "fact_gs_0294": (0, "", "", "", "", "about photography service"),
    "fact_gs_0295": (0, "", "", "", "", "one word"),
    "fact_gs_0296": (0, "", "", "", "", "reaction"),
    "fact_gs_0297": (0, "", "", "", "", "transient day description"),
    "fact_gs_0298": (0, "", "", "", "", "asking for contact info"),
    "fact_gs_0299": (0, "", "", "", "", "reaction; brother good at boba in context"),
    "fact_gs_0300": (0, "", "", "", "", "transient; brother coming"),
    "fact_gs_0301": (0, "", "", "", "", "about a movie sequel"),
    "fact_gs_0302": (1, "preference", "other_participant", "other_participant", "", "favorite shaak was okra growing up; mom packed roti for school lunch"),
    "fact_gs_0303": (0, "", "", "", "", "dad's workplace cancelled; COVID"),
    "fact_gs_0304": (1, "other", "me", "speaker", "", "involved in Yuva Kendra and Swadhyay; questioning life purpose; slowly feeling better mentally"),
    "fact_gs_0305": (0, "", "", "", "", "asking for recommendation for brother"),
    "fact_gs_0306": (1, "hobby", "other_participant", "other_participant", "", "studies 30-40 moves of chess theory"),
    "fact_gs_0307": (1, "health", "me", "speaker", "", "bad sleep (4am again); depression; considering withdrawing; doing cardio/exercises"),
    "fact_gs_0308": (0, "", "", "", "", "sports commentary"),
    "fact_gs_0309": (0, "", "", "", "", "brief food mention"),
    "fact_gs_0310": (0, "", "", "", "", "transient; dad comes home at a time"),
    "fact_gs_0311": (1, "health", "me", "speaker", "", "recovering; dad involved in medical decisions; exercise regimen"),
    "fact_gs_0312": (0, "", "", "", "", "about a package"),
    "fact_gs_0313": (0, "", "", "", "", "at airport; transient"),
    "fact_gs_0314": (0, "", "", "", "", "FaceTime logistics"),
    "fact_gs_0315": (1, "other", "other_participant", "other_participant", "", "celebrates Diwali"),
    "fact_gs_0316": (0, "", "", "", "", "joke"),
    "fact_gs_0317": (0, "", "", "", "", "transient; staying in hotel with dad"),
    "fact_gs_0318": (0, "", "", "", "", "dad's comment about Indian testing"),
    "fact_gs_0319": (0, "", "", "", "", "typo correction"),
    "fact_gs_0320": (0, "", "", "", "", "joke about eloping"),
    "fact_gs_0321": (0, "", "", "", "", "DIY suggestion"),
    "fact_gs_0322": (1, "location", "other_participant", "other_participant", "", "lives in Kips Bay; works in Hudson Yards"),
    "fact_gs_0323": (0, "", "", "", "", "reaction"),
    "fact_gs_0324": (0, "", "", "", "", "transient; packed up and flew home"),
    "fact_gs_0325": (0, "", "", "", "", "transient schedule; done with work at 8"),
    "fact_gs_0326": (0, "", "", "", "", "reaction"),
    "fact_gs_0327": (0, "", "", "", "", "transient; sister going on weekend"),
    "fact_gs_0328": (0, "", "", "", "", "asking dad about timing"),
    "fact_gs_0329": (1, "other", "me", "speaker", "", "exploring/uncertain about sexuality"),
    "fact_gs_0330": (1, "preference", "me", "speaker", "", "likes action movies; dad does too; mom doesn't"),
    "fact_gs_0331": (0, "", "", "", "", "question about math"),
    "fact_gs_0332": (0, "", "", "", "", "reaction"),
    "fact_gs_0333": (0, "", "", "", "", "sports reaction"),
    "fact_gs_0334": (0, "", "", "", "", "transient; dad disputed a charge"),
    "fact_gs_0335": (0, "", "", "", "", "encouragement about work at home"),
    "fact_gs_0336": (0, "", "", "", "", "coming to something"),
    "fact_gs_0337": (0, "", "", "", "", "about Zach being cool"),
    "fact_gs_0338": (0, "", "", "", "", "expressing pride"),
    "fact_gs_0339": (0, "", "", "", "", "reaction wrapper; mom is realtor in context"),
    "fact_gs_0340": (0, "", "", "", "", "transient emotion about ignoring"),
    "fact_gs_0341": (0, "", "", "", "", "fantasy basketball points"),
    "fact_gs_0342": (1, "preference", "me", "speaker", "", "likes Hyundai Elantra; car shopping"),
    "fact_gs_0343": (0, "", "", "", "", "transient; brother dropping off"),
    "fact_gs_0344": (0, "", "", "", "", "transient; mom scared about news"),
    "fact_gs_0345": (0, "", "", "", "", "noting friends are there"),
    "fact_gs_0346": (0, "", "", "", "", "food at gathering; dad's sauce"),
    "fact_gs_0347": (0, "", "", "", "", "transient; checking if brother is down"),
    "fact_gs_0348": (0, "", "", "", "", "momentary tech opinion about flip phones"),
    "fact_gs_0349": (0, "", "", "", "", "quoting dad"),
    "fact_gs_0350": (0, "", "", "", "", "acknowledgment"),
    "fact_gs_0351": (0, "", "", "", "", "looking for someone"),
    "fact_gs_0352": (0, "", "", "", "", "transient; hating physics"),
    "fact_gs_0353": (0, "", "", "", "", "about online classes idea"),
    "fact_gs_0354": (0, "", "", "", "", "transient; mom coming"),
    "fact_gs_0355": (0, "", "", "", "", "geography; going to Mexico in summer from context"),
    "fact_gs_0356": (0, "", "", "", "", "transient; mom booked it"),
    "fact_gs_0357": (1, "education", "other_participant", "other_participant", "", "received acceptance letter"),
    "fact_gs_0358": (0, "", "", "", "", "school project schedule"),
    "fact_gs_0359": (0, "", "", "", "", "transient; dad calling"),
    "fact_gs_0360": (0, "", "", "", "", "vague"),
    "fact_gs_0361": (0, "", "", "", "", "question about TikTok"),
    "fact_gs_0362": (0, "", "", "", "", "about gas money"),
    "fact_gs_0363": (1, "hobby", "brother", "named_entity", "", "speaker's brother bakes; speaker eats whatever brother makes"),
    "fact_gs_0364": (0, "", "", "", "", "about convincing dad to sponsor"),
    "fact_gs_0365": (0, "", "", "", "", "greeting; works at Workday in context"),
    "fact_gs_0366": (1, "health", "other_participant's dad", "named_entity", "", "dad was hospitalized for two weeks"),
    "fact_gs_0367": (0, "", "", "", "", "about cake preference"),
    "fact_gs_0368": (0, "", "", "", "", "acknowledgment"),
    "fact_gs_0369": (0, "", "", "", "", "acknowledgment"),
    "fact_gs_0370": (0, "", "", "", "", "about activities"),
    "fact_gs_0371": (0, "", "", "", "", "phone deal"),
    "fact_gs_0372": (1, "education", "brother", "named_entity", "", "brother doing culinary school externship in Delaware; speaker doing CrossFit all summer"),
    "fact_gs_0373": (0, "", "", "", "", "about brother's friends"),
    "fact_gs_0374": (0, "", "", "", "", "question about quizzes"),
    "fact_gs_0375": (0, "", "", "", "", "reaction"),
    "fact_gs_0376": (0, "", "", "", "", "transient; mom won't let them drive far"),
    "fact_gs_0377": (1, "other", "other_participant", "other_participant", "", "dad lived in an RV for years; slept on sleeping bag when visiting"),
    "fact_gs_0378": (0, "", "", "", "", "reaction"),
    "fact_gs_0379": (1, "hobby", "me", "speaker", "", "loves world building; reads super fast"),
    "fact_gs_0380": (0, "", "", "", "", "about gut feelings"),
    "fact_gs_0381": (0, "", "", "", "", "transient; dropping sister off"),
    "fact_gs_0382": (0, "", "", "", "", "agreement"),
    "fact_gs_0383": (0, "", "", "", "", "playful; Kishan punched"),
    "fact_gs_0384": (0, "", "", "", "", "reaction; mama's iPhone in context"),
    "fact_gs_0385": (0, "", "", "", "", "reaction"),
    "fact_gs_0386": (0, "", "", "", "", "transient; finished studying"),
    "fact_gs_0387": (0, "", "", "", "", "time"),
    "fact_gs_0388": (0, "", "", "", "", "about health insurance; directed to dad"),
    "fact_gs_0389": (0, "", "", "", "", "transient; mom called"),
    "fact_gs_0390": (0, "", "", "", "", "transient; car/job plan"),
    "fact_gs_0391": (0, "", "", "", "", "reaction to Unix homework"),
    "fact_gs_0392": (1, "health", "other_participant", "other_participant", "", "going through crisis: relationship break, uncle in coma, parents fighting/divorce, school stress, depression"),
    "fact_gs_0393": (0, "", "", "", "", "enthusiasm"),
    "fact_gs_0394": (0, "", "", "", "", "transient; hates life expression"),
    "fact_gs_0395": (0, "", "", "", "", "question about work; no work in context"),
    "fact_gs_0396": (1, "preference", "other_participant", "other_participant", "", "hates the cold"),
    "fact_gs_0397": (0, "", "", "", "", "transient; mom went to doctor"),
    "fact_gs_0398": (0, "", "", "", "", "transient; brother's work schedule"),
    "fact_gs_0399": (1, "hobby", "other_participant", "other_participant", "", "goes rock climbing with brother"),
    "fact_gs_0400": (0, "", "", "", "", "joke about Apple/mom not wanting iPad"),
}

# Read CSV
with open(INPUT, "r", newline="") as f:
    reader = csv.DictReader(f)
    fieldnames = reader.fieldnames
    rows = list(reader)

# Apply labels
for row in rows:
    sid = row["sample_id"]
    if sid in LABELS:
        keep, ftype, subj, res, anchor, notes = LABELS[sid]
        row["gold_keep"] = str(keep)
        row["gold_fact_type"] = ftype
        row["gold_subject"] = subj
        row["gold_subject_resolution"] = res
        row["gold_anchor_message_id"] = anchor
        row["gold_notes"] = notes
    else:
        print(f"WARNING: No label for {sid}", file=sys.stderr)

# Write back
with open(OUTPUT, "w", newline="") as f:
    writer = csv.DictWriter(f, fieldnames=fieldnames)
    writer.writeheader()
    writer.writerows(rows)

labeled = sum(1 for v in LABELS.values() if v[0] == 1)
print(f"Done. {labeled}/{len(LABELS)} labeled as keep=1 ({labeled/len(LABELS)*100:.1f}%)")

# Print type distribution
from collections import Counter
types = Counter(v[1] for v in LABELS.values() if v[0] == 1)
print(f"\nFact type distribution:")
for t, c in types.most_common():
    print(f"  {t}: {c}")
